# Generated by Django 5.0.3 on 2024-04-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Stu_name'], 'verbose_name_plural': 'stu'},
        ),
    ]
