# Generated by Django 5.0.3 on 2024-04-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_stu_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': 'Name', 'ordering': ['-Stu_name']},
        ),
    ]
